name: Playwright Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18] # tu peux ajouter 20 si tu veux tester plusieurs versions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      - name: Upload Test Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
